@EquipmentApi_HostAddress = http://localhost:5080

GET {{EquipmentApi_HostAddress}}/weatherforecast/
Accept: application/json

###

DELETE {{EquipmentApi_HostAddress}}/api/equipment/2

###

DELETE {{EquipmentApi_HostAddress}}/api/equipment/3


###

PUT {{EquipmentApi_HostAddress}}/api/crew

Content-Type: application/json

{
    "crewName" : " Cementing Crew ",
    "amountOfMembers" : 10
}

###