@EquipmentApi_HostAddress = http://localhost:5080

GET {{EquipmentApi_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{EquipmentApi_HostAddress}}/api/equipment
Content-Type: application/json

{
    "equipmentName" : "JCB",
    "equipmentAmount" : 2,
    "equipmentMake": "Samsung"
}

###

POST {{EquipmentApi_HostAddress}}/api/crew
Content-Type: application/json

{
    "crewName" : "windMillCrew",
    "amountOfMembers" : 10
}

###